### ISSUE TITLE
Wrong order of the sequence?

### ISSUE THREAD

**Issue by Journey7331** [yongsongH/IRSRMamba#1]
Hi, is this a wrong order of the sequence?
Maybe `4 3 2 1` ?

<img width="599" alt="image" src="https://github.com/yongsongH/IRSRMamba/assets/66991472/6b340de6-8151-4065-9cb7-14af2dcf27a4">

**Comment by yongsongH** [comment]
Thank you for your attention to our work.
As you mentioned, we will address this concern in the updated manuscript.
This typo will not affect the correctness of the results, please refer to the code for more details.

Thanks again :)
