### ISSUE TITLE
How to get training data？

### ISSUE THREAD

**Issue by ProBURN-E** [yongsongH/IRSRMamba#3]
Thanks for your great work!
I checked the [page](https://figshare.com/articles/dataset/IRSRMamba_Infrared_Image_Super-Resolution_via_Mamba-based_Wavelet_Transform_Feature_Modulation_Model/25835938). But only test data is provided?
I wonder how to get training dataset? Will training data pairs or the selected 265 images list in M3FD be provided?

**Comment by yongsongH** [comment]
Hi, the training dataset will be released after the manuscript is accepted. Thank you for your attention.

**Comment by ProBURN-E** [comment]
Thanks for your quick reply.
Good luck with your submission.
